name = "aggressive_peach_lark-14a0"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "aggressive_peach_lark-14a0_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "aggressive_peach_lark-14a0.wasm"
command = "npm run build:release"
